version: 2
jobs:
  build:
    parallelism: 1
    docker:
      - image: circleci/elixir:1.9.0-node
        environment:
          MIX_ENV: test
          PGHOST: 127.0.0.1
          POSTGRES_USER: circleci
      - image: circleci/postgres:10.1-alpine
        environment:
          POSTGRES_USER: circleci

    working_directory: ~/infusion

    steps:
      - checkout
      - run:
          name: Set up hex and rebar
          command: mix local.hex --force && mix local.rebar --force

      - restore_cache:
          keys:
            - v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
            - v1-mix-cache-{{ .Branch }}
            - v1-mix-cache

      - restore_cache:
          keys:
            - v1-build-cache-{{ .Branch }}
            - v1-build-cache
      - run:
          name: Install and compile Elixir dependencies
          command: mix do deps.get, compile

      - save_cache:
          key: v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths: ["deps"]
      - save_cache:
          key: v1-mix-cache-{{ .Branch }}
          paths: ["deps"]
      - save_cache:
          key: v1-mix-cache
          paths: ["deps"]

      - save_cache:
          key: v1-build-cache-{{ .Branch }}
          paths: ["_build"]
      - save_cache:
          key: v1-build-cache
          paths: ["_build"]

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Check Elixir formatting
          command: mix format --check-formatted

      - run:
          name: Create dir for test results
          command: mkdir -p /tmp/test-results/exunit

      - run:
          name: Run ExUnit tests
          command: mix coveralls.html

      - store_test_results:
          path: /tmp/test-results

      - run:
          name: Move coverage files to top-level directory
          command: sudo mv cover/excoveralls.html /exunit-coverage.html

      - store_artifacts:
          path: /exunit-coverage.html
